name: 'Extract Branch Name'
description: 'Determines the name of the currently checked out git branch'
outputs:
  branch:
    description: "The current branch"
    value: ${{ steps.extract_branch.outputs.branch }}
runs:
  using: "composite"
  steps:
    - id: extract_branch
      run: |
        if [ -z ${GITHUB_HEAD_REF+x} ] || [ -z "$GITHUB_HEAD_REF" ]; then
          BRANCH=$(echo ${GITHUB_REF#refs/heads/})
        else
          BRANCH=$(echo ${GITHUB_HEAD_REF#refs/heads/})
        fi
        echo "branch=$BRANCH" >> $GITHUB_OUTPUT
      shell: bash