# Generated by Django 3.2.6 on 2021-08-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("on_tap", "0005_auto_20210207_2019"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchlogpage",
            name="target_post_boil_volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Expected volume of finished batch prior to transfer to fermenter. Defaults to the target volume of the selected recipe if not specified.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
