# Generated by Django 4.0.3 on 2022-03-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0004_alter_taggeditem_content_type_alter_taggeditem_tag"),
        ("on_tap", "0006_batchlogpage_target_post_boil_volume"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recipepage",
            name="on_tap_reci_name_caefc3_idx",
        ),
        migrations.RemoveField(
            model_name="recipepage",
            name="name",
        ),
        migrations.AlterField(
            model_name="batchlogpagetag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
        migrations.AlterField(
            model_name="recipepagetag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
    ]
