# Generated by Django 5.2.1 on 2025-05-31 20:43

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("on_tap", "0011_alter_beveragestyle_name_and_more_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchlogpage",
            name="status",
            field=models.CharField(
                choices=[("planned", "Planned"), ("fermenting", "Fermenting"), ("complete", "Complete")],
                default="planned",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="batchlogpage",
            name="volume_units",
            field=models.CharField(
                choices=[
                    ("tsp", "Teaspoon"),
                    ("tbsp", "Tablespoon"),
                    ("fl_oz", "Fluid Oz"),
                    ("l", "Liter"),
                    ("quart", "Quart"),
                    ("gal", "Gallon"),
                ],
                default="gal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipepage",
            name="volume_units",
            field=models.CharField(
                choices=[
                    ("tsp", "Teaspoon"),
                    ("tbsp", "Tablespoon"),
                    ("fl_oz", "Fluid Oz"),
                    ("l", "Liter"),
                    ("quart", "Quart"),
                    ("gal", "Gallon"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="BatchOnTapRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("on_tap_date", models.DateField()),
                ("off_tap_date", models.DateField(blank=True, null=True)),
                (
                    "batch_log_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="on_tap_records",
                        to="on_tap.batchlogpage",
                    ),
                ),
            ],
            options={
                "ordering": ("-on_tap_date", "-off_tap_date"),
                "indexes": [
                    models.Index(fields=["on_tap_date", "off_tap_date"], name="on_tap_batc_on_tap__25a628_idx")
                ],
            },
        ),
    ]
