# Generated by Django 5.2.1 on 2025-05-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("on_tap", "0013_create_batch_on_tap_records"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="batchlogpage",
            name="on_tap_batc_on_tap__2daee1_idx",
        ),
        migrations.RemoveIndex(
            model_name="batchlogpage",
            name="on_tap_batc_off_tap_d337e6_idx",
        ),
        migrations.RemoveIndex(
            model_name="batchlogpage",
            name="on_tap_batc_status_da8bf9_idx",
        ),
        migrations.RemoveField(
            model_name="batchlogpage",
            name="off_tap_date",
        ),
        migrations.RemoveField(
            model_name="batchlogpage",
            name="on_tap_date",
        ),
        migrations.AddIndex(
            model_name="batchlogpage",
            index=models.Index(fields=["status", "brewed_date"], name="on_tap_batc_status_1ae695_idx"),
        ),
    ]
