version: '3'
services:
  database:
    image: "postgres:9.6.2"
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-developer}
        - POSTGRES_USER=${POSTGRES_USER:-developer}
        - POSTGRES_DB=${POSTGRES_DB:-bash_shell_net}
        - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    privileged: true
    volumes:
      - bash_shell_net_db:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    restart: on-failure
    volumes:
      - redis:/data
  django:
    image: bash-shell-net:dev
    # command: /bin/bash
    stdin_open: true
    tty: true
    depends_on:
      - database
      - redis
    working_dir: /home/developer/bash-shell.net
    # command: /home/developer/docker_entrypoints/dev_entrypoint.sh
    command: /usr/bin/zsh -ic 'pipenv run make setup-and-run'
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=database
      - DB_NAME=${POSTGRES_DB:-bash_shell_net}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-developer}
      - DB_USER=${POSTGRES_USER:-developer}
      - REDIS_HOST=redis
      - PIPENV_VENV_IN_PROJECT=1
      - DJANGO_SETTINGS_MODULE=bash_shell_net.settings.local
      - SHELL=/usr/bin/zsh
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      # PWD plays nicely in windows WSL, but . does not
      - ${PWD}:/home/developer/bash-shell.net/
      # More WSL workarounds
      - ${GITCONFIG_PATH:-$HOME/.gitconfig}:/home/developer/.gitconfig:ro
      - ${GITHOOKS_PATH:-$HOME/.git-hooks}:/home/developer/.git-hooks:ro
      - ${SSH_PATH:-$HOME/.ssh}:/home/developer/.ssh
volumes:
  bash_shell_net_db:
  redis:
