FROM python:3.6.4-stretch
MAINTAINER Justin Michalicek <jmichalicek@gmail.com>
EXPOSE 8000


RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated \
  inotify-tools \
  software-properties-common \
  sudo \
  vim \
  telnet \
  zsh \
  postgresql \
  postgresql-client \
  postgresql-server-dev-all \
  && apt-get autoremove && apt-get clean

RUN useradd -ms /bin/bash developer && echo "developer ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN pip install -U pip
USER developer
ENV HOME /home/developer
WORKDIR /home/developer
RUN pip install --user pipenv
VOLUME ["/home/developer/bash-shell.net/"]
VOLUME ["/home/developer/.local/share/virtualenvs/"]
RUN echo '. ~/.bashrc' >> ~/.bash_profile
RUN echo 'export PATH=/home/developer/.local/bin:$PATH' >> ~/.bashrc
RUN echo "export PATH=/home/developer/.local/bin:$PATH" >> ~/.zshenv
ENV LC_ALL=C.UTF-8 LANG=C.UTF-8 PYTHONIOENCODING=utf-8 DJANGO_SETTINGS_MODULE=bash_shell_net.settings.local SHELL=/bin/bash
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/bin/bash"]
