version: '3'
services:
  database:
    image: "postgres:9.6.2"
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-developer}
        - POSTGRES_USER=${POSTGRES_USER:-developer}
        - POSTGRES_DB=${POSTGRES_DB:-bash_shell_net}
        - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    privileged: true
    volumes:
      - bash_shell_net_db:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    restart: on-failure
  django:
    image: bash-shell-net:dev
    command: /bin/bash
    stdin_open: true
    tty: true
    depends_on:
      - database
      - redis
    working_dir: /home/developer/bash-shell.net
    # command: /home/developer/docker_entrypoints/dev_entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PYTHON_VERSION: 3.6.3
    environment:
      DB_HOST: database
      DB_NAME: ${POSTGRES_DB:-bash_shell_net}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-developer}
      DB_USER: ${POSTGRES_USER:-developer}
      REDIS_HOST: redis
      PYTHONUNBUFFERED: 'true'
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ${PWD}:/home/developer/bash-shell.net/
      - bsdev_virtulaenvs:/home/developer/.local/share/virtualenvs
volumes:
  bash_shell_net_db:
  bsdev_virtulaenvs:
