FROM python:3.7.4-stretch
MAINTAINER Justin Michalicek <jmichalicek@gmail.com>

RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  --allow-unauthenticated apt-transport-https && apt-get autoremove && apt-get clean
RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated \
  --no-install-recommends \
  inotify-tools \
  software-properties-common \
  sudo \
  vim \
  telnet \
  && apt-get autoremove && apt-get clean

RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" > /etc/apt/sources.list.d/pgdb.list
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated \
  postgresql-11 \
  postgresql-client-11 \
  postgresql-server-dev-11 \
  && apt-get autoremove && apt-get clean

RUN useradd -ms /bin/bash developer && echo "developer ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER developer
ENV HOME /home/developer
WORKDIR /home/developer
RUN sudo pip install pip --upgrade
RUN pip install pipenv --user
RUN mkdir /home/developer/bash-shell.net/
RUN echo '. ~/.bashrc' >> ~/.bash_profile
RUN echo 'export PATH=/home/developer/.local/bin:$PATH' >> ~/.bashrc
ENV LC_ALL=C.UTF-8 LANG=C.UTF-8 PYTHONIOENCODING=utf-8 DJANGO_SETTINGS_MODULE=bash_shell_net.settings.local
EXPOSE 8000
