[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
skip = ['{{ project_name }}/settings.py']
known_django = ['django']
known_wagtail = ['wagtail', 'modelcluster', 'taggit']
sections = ['FUTURE', 'STDLIB', 'DJANGO', 'WAGTAIL', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
exclude = 'migrations'
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "config.settings.local"

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "DJ"]
#ignore = ["DJ02"]

[tool.ruff.lint.extend-per-file-ignores]
"config/settings/*.py" = ["F403", "F405"] 
"wsgi.py" = ["E402"]
