[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
skip = ['{{ project_name }}/settings.py']
known_django = ['django']
known_wagtail = ['wagtail', 'modelcluster', 'taggit']
sections = ['FUTURE', 'STDLIB', 'DJANGO', 'WAGTAIL', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
exclude = 'migrations'
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "config.settings.local"

