[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 120
skip = ['{{ project_name }}/settings.py']
known_django = ['django']
known_wagtail = ['wagtail', 'modelcluster', 'taggit']
sections = ['FUTURE', 'STDLIB', 'DJANGO', 'WAGTAIL', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
