# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Automatically built from the title.', max_length=100),
        ),
    ]
