# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160907_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_markdown',
            field=models.TextField(blank=True, default=''),
        ),
    ]
