# Generated by Django 3.0.5 on 2020-05-10 14:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190606_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'bold', 'italic', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote', 'link', 'documentlink', 'image', 'embed'])), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Auto'), ('bash', 'Bash/Shell'), ('batch', 'Batch'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('css', 'CSS'), ('docker', 'Dockerfile'), ('elixir', 'Elixir'), ('go', 'Go'), ('htmldjango', 'Django Template'), ('html', 'HTML'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('lisp', 'Lisp'), ('make', 'Makefile'), ('nginx', 'NGiNX Config'), ('perl', 'Perl'), ('php', 'PHP'), ('python', 'Python'), ('jsx', 'React JSX'), ('ruby', 'Ruby'), ('erb', 'Ruby Template/ERB'), ('sass', 'SASS'), ('scss', 'SCSS'), ('sql', 'SQL'), ('terraform', 'Terraform'), ('yaml', 'YAML')], required=False)), ('filename', wagtail.core.blocks.CharBlock(default='', required=False)), ('display_filename', wagtail.core.blocks.BooleanBlock(default=True, required=False)), ('code', wagtail.core.blocks.TextBlock(default='', required=False)), ('line_numbers', wagtail.core.blocks.ChoiceBlock(choices=[('', 'None'), ('table', 'Table'), ('inline', 'Inline')], required=False))])), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('other_page', wagtail.core.blocks.PageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(template='wagtail_blocks/image.html')), ('image_detail', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(label='Caption', max_length=200, required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False)), ('license_url', wagtail.core.blocks.URLBlock(required=False)), ('license_name', wagtail.core.blocks.CharBlock(required=False))])), ('image_gallery', wagtail.core.blocks.StructBlock([('image_items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(label='Caption', max_length=200, required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False)), ('license_url', wagtail.core.blocks.URLBlock(required=False)), ('license_name', wagtail.core.blocks.CharBlock(required=False))]), label='Image'))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('text', wagtail.core.blocks.TextBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True, default=None, null=True),
        ),
    ]
