# Generated by Django 3.0.8 on 2020-08-01 13:45

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_tap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beveragestyle',
            name='external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipefermentable',
            name='maltster',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, default='', max_length=100),
        ),
    ]
