# Generated by Django 3.0.5 on 2020-05-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_tap', '0002_recipepageindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beveragestyle',
            name='beverage_type',
            field=models.CharField(blank=True, choices=[('ale', 'Ale'), ('lager', 'Lager'), ('cider', 'Cider'), ('mead', 'Mead'), ('mixed', 'Mixed')], db_index=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='recipehop',
            name='beta_acid_percent',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='brewer',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
