# Generated by Django 3.0.5 on 2020-05-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_tap', '0003_auto_20200516_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='volume_units',
            field=models.CharField(choices=[('fl_oz', 'Fluid Oz.'), ('l', 'Liters'), ('gal', 'Gallons'), ('quart', 'Quarts')], default='gal', max_length=10),
            preserve_default=False,
        ),
    ]
