# Generated by Django 3.0.5 on 2020-05-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_tap', '0004_recipepage_volume_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeyeast',
            name='yeast_type',
            field=models.CharField(choices=[('dry', 'Dry'), ('liquid', 'Liquid')], default='dry', max_length=25),
            preserve_default=False,
        ),
    ]
