# Generated by Django 3.0.5 on 2020-05-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_tap', '0006_auto_20200530_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipehop',
            name='use_time',
            field=models.IntegerField(default=0, help_text='Time in minutes. Specific meaning varies by use type.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipemiscingredient',
            name='use_time',
            field=models.IntegerField(default=0, help_text='Amount of time the misc was boiled, steeped, mashed, etc in minutes.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipepage',
            name='boil_time',
            field=models.IntegerField(default=0, help_text='Total time to boil the wort in minutes.'),
            preserve_default=False,
        ),
    ]
