# Generated by Django 3.0.5 on 2020-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_tap', '0007_auto_20200530_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='A one or two sentence description of the recipe.'),
        ),
    ]
