# Generated by Django 3.0.5 on 2020-06-28 21:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_tap', '0008_recipepage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='boil_gravity',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='final_gravity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='ibus_tinseth',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='original_gravity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=4),
        ),
    ]
