# Generated by Django 3.0.5 on 2020-07-18 20:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_tap', '0009_auto_20200628_2154'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='batchlogpage',
            name='on_tap_batc_is_on_t_d825cf_idx',
        ),
        migrations.RemoveField(
            model_name='batchlogpage',
            name='is_on_tap',
        ),
        migrations.AddField(
            model_name='batchlogpage',
            name='off_tap_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='ibus_tinseth',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddIndex(
            model_name='batchlogpage',
            index=models.Index(fields=['on_tap_date'], name='on_tap_batc_on_tap__2daee1_idx'),
        ),
        migrations.AddIndex(
            model_name='batchlogpage',
            index=models.Index(fields=['off_tap_date'], name='on_tap_batc_off_tap_d337e6_idx'),
        ),
        migrations.AddIndex(
            model_name='batchlogpage',
            index=models.Index(fields=['brewed_date'], name='on_tap_batc_brewed__595334_idx'),
        ),
        migrations.AddIndex(
            model_name='batchlogpage',
            index=models.Index(fields=['status', 'brewed_date', 'on_tap_date', 'off_tap_date'], name='on_tap_batc_status_da8bf9_idx'),
        ),
    ]
