# Generated by Django 3.0.5 on 2020-07-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('on_tap', '0011_batchlogindexpage_recipeindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipePageIndex',
        ),
    ]
