# Generated by Django 3.0.5 on 2020-05-10 15:04

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0004_auto_20200510_1459",
        ),  # not really but django is being dumb about this. It really should be the first one.
    ]

    operations = [
        CITextExtension(),
    ]
