name: Tests And Linting
on:
  push:
    branches:
    - main
    - production
  pull_request:
    branches:
    - main
env:
  REGISTRY: registry.gitlab.com

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Extract Branch Name
        uses: ./.github/actions/extract-branch-name
        id: extract_branch
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
          username: ${{ env.DOCKER_CONTAINER_REGISTRY_USER }}
          password: ${{ env.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGISTRY}}/${GITHUB_REPOSITORY,,}:${{ steps.extract_branch.outputs.branch }}_${GITHUB_SHA} .
          docker push ${{ env.REGISTRY}}/${GITHUB_REPOSITORY,,}:${{ steps.extract_branch.outputs.branch }}_${GITHUB_SHA}
  back_end_tests:
    name: Back End Tests
    needs: build_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
        username: ${{ env.DOCKER_CONTAINER_REGISTRY_USER }}
        password: ${{ env.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Setup Image
      uses: ./.github/actions/setup-docker-image
    - name: Tests
      shell: bash
      run: docker compose --profile=ci run --service-ports --rm django_ci python manage.py test
  flake8:
    name: Flake8
    needs: build_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
        username: ${{ env.DOCKER_CONTAINER_REGISTRY_USER }}
        password: ${{ env.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Setup Image
      uses: ./.github/actions/setup-docker-image
    - name: Flake8
      run: docker compose --profile=ci run --service-ports --rm django_ci make flake8
  isort:
    name: isort
    needs: build_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
        username: ${{ env.DOCKER_CONTAINER_REGISTRY_USER }}
        password: ${{ env.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Setup Image
      uses: ./.github/actions/setup-docker-image
    - name: isort
      run: docker compose --profile=ci run --service-ports --rm django_ci make isort-check
  djhtml:
    name: djhtml
    needs: build_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
        username: ${{ env.DOCKER_CONTAINER_REGISTRY_USER }}
        password: ${{ env.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Setup Image
      uses: ./.github/actions/setup-docker-image
    - name: djhtml
      run: docker compose --profile=ci run --service-ports --rm django_ci make djhtml-check
  static_analysis:
    name: Static Analysis
    needs: build_image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_CONTAINER_REGISTRY }}
        username: ${{ env.DOCKER_CONTAINER_REGISTRY_USER }}
        password: ${{ env.DOCKER_CONTAINER_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Setup Image
      uses: ./.github/actions/setup-docker-image
    - name: mypy
      run: docker compose --profile=ci run --service-ports --rm django_ci make mypy