FROM debian:stretch-backports
MAINTAINER Justin Michalicek <jmichalicek@gmail.com>
EXPOSE 8000

RUN apt-get update && apt-get install -y --force-yes \
    autoconf \
    bind9-host \
    bison \
    build-essential \
    coreutils \
    curl \
    daemontools \
    dnsutils \
    git \
    inotify-tools \
    libbz2-dev \
    libcurl4-openssl-dev \
    libev-dev \
    libevent-dev \
    libffi-dev \
    libglib2.0-dev \
    libjpeg-dev \
    libpq-dev \
    libpq5 \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libuv1-dev \
    libxml2-dev \
    libxslt-dev \
    postgresql \
    postgresql-client \
    postgresql-server-dev-all \
    python \
    sudo \
    tar \
    telnet \
    vim \
    wget \
    zip \
    zlib1g-dev

RUN useradd -ms /bin/bash developer && echo "developer ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# set dev db to trust all local users
RUN sed -i -e 's#^host\s\+all\s\+all\s\+127.0.0.1\/32\s\+md5$#host    all all 127.0.0.1/32    trust#' /etc/postgresql/9.6/main/pg_hba.conf

USER developer
ENV HOME /home/developer
WORKDIR /home/developer
RUN echo '. ~/.bashrc' >> ~/.bash_profile

# python install
RUN wget https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tgz
RUN tar xvf Python-3.6.2.tgz
WORKDIR Python-3.6.2
RUN ./configure --prefix=/home/developer/python3 && make && make install
RUN echo 'export PATH=/home/developer/python3/bin:$PATH' >> ~/.bashrc
RUN PATH=/home/developer/python3/bin:$PATH pip3 install pipenv
# end new stuff

USER root
RUN mkdir /home/developer/docker_entrypoints
COPY _docker/dev_entrypoint.sh /home/developer/docker_entrypoints/dev_entrypoint.sh
RUN chown developer /home/developer/docker_entrypoints/dev_entrypoint.sh && chmod 755 /home/developer/docker_entrypoints/dev_entrypoint.sh

USER developer
## for now do not make postgres data permanent
## VOLUME ["/var/lib/postgresql/9.4/main"]
VOLUME ["/home/developer/bash-shell.net/"]
VOLUME ["/home/developer/.local/share/virtualenvs/"]

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8 PYTHONIOENCODING=utf-8 DJANGO_SETTINGS_MODULE=bash_shell_net.settings.local SHELL=/bin/bash
ENV PATH=/home/developer/python3/bin:$PATH
CMD ["/bin/bash"]
